email: me@raknam.fr
description: >-
  Bla bla bla
baseurl: ""
url: "https://000.ovh"

twitter_username: raknam
github_username:  raknam
show_downloads:   false
# google_analytics:

plugins:
  - jekyll-coffeescript

exclude:
  - .idea

tools:
  - base64
  - md5
  - sha1
  - sha256
  - sha512
  - sha384
  - urlencode